google:
    recaptcha:
        secret: xxx
logging:
    file:
        path: ./showYourKnowledgeLogs
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE # Eger trace yaparsak SQL'de giden parametrelerin icerigini de goruruz
spring:
    datasource:
        #For docker --> url: jdbc:mysql://host.docker.internal:3306/gosterbilgini?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false&useLegacyDatetimeCode=false&serverTimezone=Turkey
        url: jdbc:mysql://localhost:3306/gosterbilgini?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false&useLegacyDatetimeCode=false&serverTimezone=Turkey
        username: root
        password: root
        #driver-class-name: com.mysql.jdbc.Driver
        #initialization-mode=always: always # always olursa data.sql'i calistirir
    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none #create veya cerate-drop modunda hibernate entitylere göre tabloları oluşturur ve import.sql çalışır
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
        show-sql: false
    mail:
        #Bunlari sifrele MAIL
        host: smtp.gmail.com
        password: password
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    connectiontimeout: 10000
                    ssl:
                        trust: smtp.gmail.com
                    starttls:
                        enable: true
                    timeout: 10000
                    writetimeout: 10000
                    #starttls:
                    #   required: true
                    #socketFactory:
                    #   class: javax.net.ssl.SSLSocketFactory
        username: userName
        #default-encoding: UTF-8
        #protocol: smtp
        #test-connection: false
pom:
    version: @project.version@
springfox:
    documentation:
        auto-startup: true
        swagger:
            v2:
                path: /v2/api-docs